kind: wasmer.io/App.v0
name: php-db-latency-regional
owner: wasmer-tests
package: .
domains:
- php-db-latency-regional.wasmer.app
- php-db-latency-regional2.wasmer.app
locality:
  regions:
  - us-ashburn
