kind: wasmer.io/App.v0
name: php-db-latency-regional
owner: wasmer-tests
package: '.'
capabilities:
  database:
    engine: mysql
domains:
- php-db-latency-regional.wasmer.dev
# - php-db-latency-regional2.wasmer.app
locality:
  regions:
  - fi-helsinki
  #- us-ashburn
